management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    im:
      turms: DEBUG

spring:
  netty:
    leak-detection: paranoid

############################### Turms ###############################

turms:
  logging:
    enable-console-appender: true
  service:
    client-api:
      logging:
        included-request-categories:
          - category: all
    fake:
      enabled: true
      clear-all-collections-before-faking: true
    message:
      check-if-target-active-and-not-deleted: false
turms-plugin:
  minio:
    retry:
      enabled: false