management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    im:
      turms: DEBUG

############################### Turms ###############################

turms:
  logging:
    enable-console-appender: true
  service:
    client-api:
      logging:
        included-request-categories:
          - category: all
    message:
      check-if-target-active-and-not-deleted: false
    mock:
      enabled: true
      clear-all-collections-before-mocking: true
turms-plugin:
  minio:
    retry:
      enabled: false