# HTTP(S) configuration
server:
  address: 0.0.0.0
  port: 8510
  ssl:
    enabled: false # Enable SSL if needed. Make sure to mutate HTTP requests to HTTPS requests, or Netty will throw NotSslRecordException
    key-store: classpath:keystore-test.p12 # keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias turms -keystore keystore-test.p12 -storetype PKCS12 -storepass imturms
    key-store-type: PKCS12
    key-store-password: imturms
    key-alias: turms
spring:
  application:
    name: turms
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null
    time-zone: UTC
    mapper:
      propagate-transient-marker: true
  profiles:
    active: dev
    group:
      dev:
        - dev
        - dev-latest
      test:
        - test
        - test-latest
      prod:
        - prod
        - prod-latest
  boot:
    admin:
      client:
        auto-deregistration: true
        url: http://localhost:9514
        username: turms
        password: turms
        register-once: false
  webflux:
    format:
      date-time: yyyy-MM-dd'T'HH:mm:ssX
  codec:
    max-in-memory-size: 64KB
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.MetricsEndpointAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
management:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
  # Prometheus is enabled by default. Uncomment the following lines to disable it.
  #  metrics:
  #    enable:
  #      prometheus: false
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: info,health,env,heapdump,threaddump,metrics,prometheus
springdoc:
  show-actuator: true
  swagger-ui:
    doc-expansion: none

############################### Turms ###############################

turms:
  cluster:
    id: turms
    discovery:
      client-ssl:
        enabled: false # Enable SSL if needed
        enabled-protocols: TLSv1.2,TLSv1.3
        key-store: classpath:keystore-test.p12 # keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias turms -keystore keystore-test.p12 -storetype PKCS12 -storepass imturms
        key-store-type: PKCS12
        key-store-password: imturms
        key-alias: turms
      server-ssl:
        enabled: false # Enable SSL if needed
        enabled-protocols: TLSv1.2,TLSv1.3
        key-store: classpath:keystore-test.p12 # keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias turms -keystore keystore-test.p12 -storetype PKCS12 -storepass imturms
        key-store-type: PKCS12
        key-store-password: imturms
        key-alias: turms
#turms-plugin:
#  mock:
#    enabled: true