management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    im:
      turms: DEBUG

############################### Turms ###############################

turms:
  cluster:
    shared-config:
      mongo:
        uri: mongodb://localhost:29510/turms-config-dev
  service:
    client-api:
      logging:
        included-request-categories:
          - category: all
        included-response-categories:
          - category: all
        included-notification-categories:
          - category: all
    mock:
      enabled: true
      clear-all-collections-before-mocking: true
    mongo:
      admin:
        uri: mongodb://localhost:29510/turms-dev
      user:
        uri: mongodb://localhost:29510/turms-dev
      group:
        uri: mongodb://localhost:29510/turms-dev
      conversation:
        uri: mongodb://localhost:29510/turms-dev
      message:
        uri: mongodb://localhost:29510/turms-dev
turms-plugin:
  minio:
    retry:
      enabled: false