name: turms_client_dart
version: 1.0.0
homepage: https://github.com/turms-im/turms

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  fixnum: ^1.0.0
  protobuf: ^2.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
