logging:
  level:
    im:
      turms: DEBUG

############################### Turms ###############################

turms:
  cluster:
    shared-config:
      mongo:
        uri: mongodb://localhost:27017/turms-config-dev
  gateway:
    client-api:
      logging:
        included-request-categories:
          - category: all
        included-notification-categories:
          - category: all
      return-reason-for-server-error: true
    mongo:
      user:
        uri: mongodb://localhost:27017/turms-dev
    fake:
      enabled: true
    tcp:
      # For testing purposes
      enabled: true
  logging:
    enable-console-appender: true