logging:
  level:
    im:
      turms: DEBUG

############################### Turms ###############################

turms:
  cluster:
    shared-config:
      mongo:
        uri: mongodb://localhost:29510/turms-config-dev
  gateway:
    client-api:
      logging:
        included-request-categories:
          - category: all
        included-response-categories:
          - category: all
      return-reason-for-server-error: true
    mongo:
      user:
        uri: mongodb://localhost:29510/turms-dev