# The server properties for metrics APIs (not for WebSocket)
server:
  address: 0.0.0.0
  port: 9510

turms:
  cluster:
    connection:
      client:
        ssl:
          enabled: false # Enable SSL if needed
          enabled-protocols: TLSv1.2,TLSv1.3
          key-store: classpath:keystore-test.p12 # keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias turms -keystore keystore-test.p12 -storetype PKCS12 -storepass imturms
          key-store-type: PKCS12
          key-store-password: imturms
          key-alias: turms
      server:
        ssl:
          enabled: false # Enable SSL if needed
          enabled-protocols: TLSv1.2,TLSv1.3
          key-store: classpath:keystore-test.p12 # keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias turms -keystore keystore-test.p12 -storetype PKCS12 -storepass imturms
          key-store-type: PKCS12
          key-store-password: imturms
          key-alias: turms
  gateway:
    websocket:
      enabled: true
      port: 10510
      ssl:
        enabled: false # Enable SSL if needed. Make sure to mutate HTTP requests to HTTPS requests, or Netty will throw NotSslRecordException
        enabled-protocols: TLSv1.2,TLSv1.3
        key-store: classpath:keystore-test.p12 # keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias turms -keystore keystore-test.p12 -storetype PKCS12 -storepass imturms
        key-store-type: PKCS12
        key-store-password: imturms
        key-alias: turms
    tcp:
      port: 11510
      ssl:
        enabled: false # Enable SSL if needed
        enabled-protocols: TLSv1.2,TLSv1.3
        key-store: classpath:keystore-test.p12 # keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias turms -keystore keystore-test.p12 -storetype PKCS12 -storepass imturms
        key-store-type: PKCS12
        key-store-password: imturms
        key-alias: turms
    udp:
      # Disable UDP currently until clients support UDP
      enabled: false
      port: 12510

# Spring configuration
spring:
  profiles:
    active: prod
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.CompositeMeterRegistryAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.data.RepositoryMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.MetricsEndpointAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
    serialization:
      fail-on-empty-beans: false
    time-zone: UTC
    mapper:
      propagate-transient-marker: true
  netty:
    leak-detection: simple
management:
  endpoint:
    metrics:
      # We use our own implementation
      enabled: false
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: info,health,env,threaddump
