management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    im:
      turms: DEBUG

spring:
  netty:
    leak-detection: paranoid

############################### Turms ###############################

turms:
  cluster:
    connection:
      server:
        port-auto-increment: true
    shared-config:
      mongo:
        uri: mongodb://localhost:27017/turms-config-dev
  logging:
    console:
      enabled: true
  service:
    client-api:
      logging:
        included-notification-categories:
          - category: all
    fake:
      enabled: true
    message:
      check-if-target-active-and-not-deleted: false
    mongo:
      admin:
        uri: mongodb://localhost:27017/turms-dev
      user:
        uri: mongodb://localhost:27017/turms-dev
      group:
        uri: mongodb://localhost:27017/turms-dev
      conversation:
        uri: mongodb://localhost:27017/turms-dev
      message:
        uri: mongodb://localhost:27017/turms-dev
        temperature:
          enabled: true
          hot:
            shards:
              - shard01
          warm:
            shards:
              - shard01
          cold:
            shards:
              - shard01
          frozen:
            shards:
              - shard01
turms-plugin:
  minio:
    retry:
      enabled: false