name: Publish turms-gateway

on: [ push, pull_request ]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build turms-gateway image
        run: DOCKER_BUILDKIT=1 docker build --rm=false -t "ghcr.io/turms-im/turms-gateway:latest" -f turms-gateway/Dockerfile .

      - name: Docker login
        if: ${{ github.ref == 'refs/heads/master' }}
        run: docker login ghcr.io -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish turms-gateway
        if: ${{ github.ref == 'refs/heads/master' }}
        run: docker push "ghcr.io/turms-im/turms-gateway:latest"