name: Publish turms-admin

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Build turms-admin image
        # FIXME: We use the root context currently because turms-admin requires turms-client-js,
        # which doesn't have a publish workflow for now.
        run: DOCKER_BUILDKIT=1 docker build --rm=false -t "ghcr.io/turms-im/turms-admin:latest" -f turms-admin/Dockerfile .

      - name: Docker login
        run: docker login ghcr.io -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish turms-admin
        run: docker push "ghcr.io/turms-im/turms-admin:latest"